quarkus.application.name=HowMuchReps

quarkus.datasource.db-kind=[YOUR DATASOURCE TYPE HERE]
quarkus.http.root-path=api/
quarkus.datasource.jdbc.url=[YOUR DATASOURCE URL HERE]
quarkus.datasource.username=[YOUR DATASOURCE USERNAME HERE]
quarkus.datasource.password=[YOUR DATASOURCE PASSWORD HERE]