quarkus.application.name=HowMuchReps

quarkus.datasource.db-kind=postgresql
quarkus.http.root-path=api/
quarkus.datasource.jdbc.url=${quarkus.datasource.jdbc.url}
quarkus.datasource.username=${quarkus.datasource.username}
quarkus.datasource.password=${quarkus.datasource.password}
